# app/services/transcript_service.py

from youtube_transcript_api import (
    YouTubeTranscriptApi,
    TranscriptsDisabled,
    NoTranscriptFound
)
from youtube_transcript_api.formatters import TextFormatter
from xml.etree.ElementTree import ParseError


def get_video_transcript(video_id: str) -> str:
    try:
        transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)

        try:
            # Prefer manually created English transcript
            transcript = transcript_list.find_manually_created_transcript(['en'])
        except Exception:
            # Fallback to autogenerated English
            transcript = transcript_list.find_generated_transcript(['en'])

        formatter = TextFormatter()
        return formatter.format_transcript(transcript.fetch())

    except (ParseError, TranscriptsDisabled, NoTranscriptFound, Exception):
        raise ValueError(
            "Transcript not accessible for this video in this environment"
        )
