from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
import logging

from app.schemas.request import QueryRequest
from app.schemas.response import QueryResponse

# New Unified Services
from app.services.rag_service import RAGService 
from app.services.orchestrator import Orchestrator
from app.services.youtube_service import find_relevant_chapters
from app.services.quota_service import check_and_update_quota

logger = logging.getLogger(__name__)
router = APIRouter()

# Initialize services
rag_service = RAGService()
orchestrator = Orchestrator()

@router.post("/ask", response_model=QueryResponse)
async def ask_question(request: QueryRequest):
    """
    Standard RAG endpoint (Non-streaming).
    Returns the full answer once generation is complete.
    """
    try:
        # 1. Quota Check
        remaining = check_and_update_quota(request.client_id)
        
        # 2. Ingestion Check
        video_data = await orchestrator.process_video(request.video_id, request.video_url)
        if not video_data or not video_data.get("text"):
            raise HTTPException(status_code=404, detail="Could not retrieve content for this video.")

        # 3. Vector Ingestion
        rag_service.ingest_video(request.video_id, video_data["text"])

        # 4. Keyword Citations
        metadata = video_data.get("metadata", {})
        chapters = metadata.get("chapters", [])
        cited_chapters = find_relevant_chapters(request.question, chapters)

        # 5. Get Full Answer
        answer = rag_service.get_answer(request.video_id, request.question)

        return {
            "answer": answer,
            "citations": cited_chapters,
            "remaining_queries": remaining,
        }

    except Exception as e:
        logger.error(f"[ASK API ERROR] {e}")
        raise HTTPException(status_code=500, detail="An internal error occurred.")

@router.post("/ask-stream")
async def ask_stream(request: QueryRequest):
    """
    Streaming RAG endpoint.
    Yields chunks of text as they are generated by the LLM.
    """
    logger.info(f"🚀 Streaming request received for Video ID: {request.video_id}")

    try:
        # 1. Quota Check (Optional: You can skip for local testing)
        check_and_update_quota(request.client_id)

        # 2. Ensure Video is processed
        video_data = await orchestrator.process_video(request.video_id, request.video_url)
        if not video_data or not video_data.get("text"):
            raise HTTPException(status_code=404, detail="Video content unavailable.")

        # 3. Ingest into Vector DB
        rag_service.ingest_video(request.video_id, video_data["text"])

        # 4. Return the Async Generator
        # IMPORTANT: We use rag_service.get_answer_stream (the one using .astream())
        return StreamingResponse(
            rag_service.get_answer_stream(request.video_id, request.question),
            media_type="text/plain"
        )

    except Exception as e:
        logger.error(f"[STREAM API ERROR] {e}")
        # In streaming, if the headers are already sent, this might not reach the client properly.
        # But for the initial connection, it works.
        raise HTTPException(status_code=500, detail=str(e))